-- ================================================================
-- E-Commerce App - Oracle Database Schema
-- Run this in Oracle SQL Developer or SQL*Plus
-- ================================================================

-- SEQUENCES (auto-increment)
CREATE SEQUENCE SEQ_USERS       START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PRODUCTS    START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ORDERS      START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_ORDER_ITEMS START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE SEQ_PAYMENTS    START WITH 1 INCREMENT BY 1 NOCACHE;

-- USERS
CREATE TABLE USERS (
    USER_ID     NUMBER PRIMARY KEY,
    USERNAME    VARCHAR2(100) NOT NULL,
    EMAIL       VARCHAR2(150) UNIQUE NOT NULL,
    PASSWORD    VARCHAR2(255) NOT NULL,
    ROLE        VARCHAR2(20)  DEFAULT 'User' CHECK (ROLE IN ('Admin','User')),
    PHONE       VARCHAR2(15),
    ADDRESS     VARCHAR2(500),
    IS_ACTIVE   NUMBER(1)     DEFAULT 1,
    CREATED_AT  DATE          DEFAULT SYSDATE
);
CREATE OR REPLACE TRIGGER TRG_USERS BEFORE INSERT ON USERS FOR EACH ROW
BEGIN SELECT SEQ_USERS.NEXTVAL INTO :NEW.USER_ID FROM DUAL; END;
/

-- PRODUCTS
CREATE TABLE PRODUCTS (
    PRODUCT_ID  NUMBER PRIMARY KEY,
    NAME        VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    PRICE       NUMBER(10,2)  NOT NULL,
    STOCK       NUMBER        DEFAULT 0,
    CATEGORY    VARCHAR2(100),
    IMAGE_URL   VARCHAR2(500),
    IS_ACTIVE   NUMBER(1)     DEFAULT 1,
    CREATED_AT  DATE          DEFAULT SYSDATE
);
CREATE OR REPLACE TRIGGER TRG_PRODUCTS BEFORE INSERT ON PRODUCTS FOR EACH ROW
BEGIN SELECT SEQ_PRODUCTS.NEXTVAL INTO :NEW.PRODUCT_ID FROM DUAL; END;
/

-- ORDERS
CREATE TABLE ORDERS (
    ORDER_ID          NUMBER PRIMARY KEY,
    USER_ID           NUMBER NOT NULL REFERENCES USERS(USER_ID),
    TOTAL_AMOUNT      NUMBER(10,2) NOT NULL,
    STATUS            VARCHAR2(50) DEFAULT 'Pending'
                      CHECK (STATUS IN ('Pending','Confirmed','Shipped','Delivered','Cancelled')),
    PAYMENT_METHOD    VARCHAR2(50) CHECK (PAYMENT_METHOD IN ('COD','Online','UPI','Card')),
    PAYMENT_STATUS    VARCHAR2(50) DEFAULT 'Pending'
                      CHECK (PAYMENT_STATUS IN ('Pending','Paid','Refunded')),
    DELIVERY_ADDRESS  VARCHAR2(500),
    ORDER_DATE        DATE DEFAULT SYSDATE
);
CREATE OR REPLACE TRIGGER TRG_ORDERS BEFORE INSERT ON ORDERS FOR EACH ROW
BEGIN SELECT SEQ_ORDERS.NEXTVAL INTO :NEW.ORDER_ID FROM DUAL; END;
/

-- ORDER_ITEMS
CREATE TABLE ORDER_ITEMS (
    ITEM_ID       NUMBER PRIMARY KEY,
    ORDER_ID      NUMBER NOT NULL REFERENCES ORDERS(ORDER_ID),
    PRODUCT_ID    NUMBER NOT NULL REFERENCES PRODUCTS(PRODUCT_ID),
    PRODUCT_NAME  VARCHAR2(200),
    QUANTITY      NUMBER       NOT NULL,
    UNIT_PRICE    NUMBER(10,2) NOT NULL,
    TOTAL_PRICE   NUMBER(10,2) NOT NULL
);
CREATE OR REPLACE TRIGGER TRG_ORDER_ITEMS BEFORE INSERT ON ORDER_ITEMS FOR EACH ROW
BEGIN SELECT SEQ_ORDER_ITEMS.NEXTVAL INTO :NEW.ITEM_ID FROM DUAL; END;
/

-- PAYMENTS
CREATE TABLE PAYMENTS (
    PAYMENT_ID      NUMBER PRIMARY KEY,
    ORDER_ID        NUMBER NOT NULL REFERENCES ORDERS(ORDER_ID),
    AMOUNT          NUMBER(10,2) NOT NULL,
    METHOD          VARCHAR2(50),
    STATUS          VARCHAR2(50) DEFAULT 'Pending'
                    CHECK (STATUS IN ('Pending','Success','Failed')),
    TRANSACTION_ID  VARCHAR2(100),
    PAYMENT_DATE    DATE DEFAULT SYSDATE
);
CREATE OR REPLACE TRIGGER TRG_PAYMENTS BEFORE INSERT ON PAYMENTS FOR EACH ROW
BEGIN SELECT SEQ_PAYMENTS.NEXTVAL INTO :NEW.PAYMENT_ID FROM DUAL; END;
/

-- DEFAULT DATA
INSERT INTO USERS (USERNAME,EMAIL,PASSWORD,ROLE,PHONE,ADDRESS)
VALUES ('Admin','admin@shop.com','Admin@123','Admin','9999999999','Admin Office, Surat');

INSERT INTO PRODUCTS (NAME,DESCRIPTION,PRICE,STOCK,CATEGORY,IMAGE_URL)
VALUES ('Laptop Pro 15','Intel i5, 8GB RAM, 256GB SSD',45999,10,'Electronics','https://via.placeholder.com/300x200?text=Laptop');

INSERT INTO PRODUCTS (NAME,DESCRIPTION,PRICE,STOCK,CATEGORY,IMAGE_URL)
VALUES ('Wireless Mouse','Ergonomic, USB receiver',599,50,'Electronics','https://via.placeholder.com/300x200?text=Mouse');

INSERT INTO PRODUCTS (NAME,DESCRIPTION,PRICE,STOCK,CATEGORY,IMAGE_URL)
VALUES ('Running Shoes','Lightweight breathable shoes',1299,30,'Footwear','https://via.placeholder.com/300x200?text=Shoes');

INSERT INTO PRODUCTS (NAME,DESCRIPTION,PRICE,STOCK,CATEGORY,IMAGE_URL)
VALUES ('Laptop Backpack','30L waterproof with laptop compartment',899,25,'Bags','https://via.placeholder.com/300x200?text=Bag');

COMMIT;

-- VIEW for Reports
CREATE OR REPLACE VIEW V_ORDER_SUMMARY AS
SELECT O.ORDER_ID,U.USERNAME,U.EMAIL,O.TOTAL_AMOUNT,O.STATUS,O.PAYMENT_METHOD,O.ORDER_DATE
FROM ORDERS O JOIN USERS U ON O.USER_ID=U.USER_ID;
